steps:
  # Paso 1: Construye la imagen de Docker para el frontend, pasando la variable de entorno
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - build
    - --tag=gcr.io/$PROJECT_ID/todo-app
    - --build-arg=NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL
    - .

  # Paso 2: Sube la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-app']

  # Paso 3: Despliega el frontend en Cloud Run
- name: 'google/cloud-sdk'
  args:
    - gcloud
    - run
    - deploy
    - todo-app
    - --image
    - gcr.io/$PROJECT_ID/todo-app
    - --region
    - us-central1
    - --allow-unauthenticated
    - --platform
    - managed

# Mueve el 'timeout' a este nivel, fuera de 'options'
timeout: '1200s'

# Opciones para la compilación, incluyendo la solución para los logs
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

# Sustituciones para variables de entorno no sensibles
substitutions:
  _NEXT_PUBLIC_API_URL: 'https://34.96.115.12.nip.io/api/todo'