steps:
  # Paso 1: Construye la imagen de Docker para el frontend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-app', '.']

  # Paso 2: Sube la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-app']

  # Paso 3: Despliega el frontend en Cloud Run
- name: 'google/cloud-sdk'
  args:
    - gcloud
    - run
    - deploy
    - todo-app
    - --image
    - gcr.io/$PROJECT_ID/todo-app
    - --region
    - us-central1
    - --allow-unauthenticated
    - --platform
    - managed
    - --set-env-vars
    - NEXT_PUBLIC_API_URL=https://34.96.115.12.nip.io/api/todo

# timeout para la construcción (20 minutos) - por defecto es 10 minutos
timeout: '1200s'

# Opciones para la compilación, incluyendo la solución para los logs
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET